apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-api-config
  namespace: fiap-gamestore
  labels:
    app: notifications-api
data:
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  QUEUE_USER_CREATED: "user-created-event"
  QUEUE_PAYMENT_PROCESSED: "payment-processed-event"
