apiVersion: v1
kind: Secret
metadata:
  name: notifications-api-secret
  namespace: fiap-gamestore
  labels:
    app: notifications-api
type: Opaque
stringData:
  RABBITMQ_USERNAME: "guest"
  RABBITMQ_PASSWORD: "guest"
