{{- if .Values.global.externalSecretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.global.externalSecretStore.name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.global.externalSecretStore.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.global.externalSecretStore.serviceAccountRef.name }}
            namespace: {{ .Values.global.externalSecretStore.serviceAccountRef.namespace }}
{{- end }}
