{{- range $name, $service := .Values.services }}
{{- range $externalSecret := $service.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $externalSecret.name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    {{- include "fcg-platform.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ default "1h" $externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ $.Values.global.externalSecretStore.name }}
    kind: {{ $.Values.global.externalSecretStore.kind }}
  target:
    name: {{ $externalSecret.name }}
    creationPolicy: Owner
  data:
    {{- toYaml $externalSecret.data | nindent 4 }}
---
{{- end }}
{{- end }}
