apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
  namespace: fiap-gamestore
  labels:
    app: payments-api
    component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
        component: worker
    spec:
      initContainers:
      - name: wait-for-rabbitmq
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          until nc -z rabbitmq-service 5672; do
            echo "Waiting for rabbitmq-service..."
            sleep 2
          done
          echo "RabbitMQ is ready!"
      containers:
      - name: payments-api
        image: payments-api:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: payments-api-config
        - secretRef:
            name: payments-api-secret
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
