apiVersion: v1
kind: Secret
metadata:
  name: payments-api-secret
  namespace: fiap-gamestore
  labels:
    app: payments-api
type: Opaque
stringData:
  RabbitMQ__Username: "guest"
  RabbitMQ__Password: "guest"
