apiVersion: v1
kind: Service
metadata:
  name: payments-api-service
  namespace: fiap-gamestore
  labels:
    app: payments-api
    component: worker
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: payments-api
