apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
  namespace: fiap-gamestore
  labels:
    app: catalog-api
type: Opaque
stringData:
  postgres-connection-string: "Host=postgres-catalog-service;Port=5432;Database=catalogdb;Username=admin;Password=admin123"
  rabbitmq-username: "guest"
  rabbitmq-password: "guest"
