apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  namespace: fiap-gamestore
  labels:
    app: rabbitmq
    component: message-broker
    service-type: external
spec:
  type: NodePort
  ports:
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: management
    nodePort: 31672
  selector:
    app: rabbitmq
