apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-catalog-config
  namespace: fiap-gamestore
  labels:
    app: postgres-catalog
    component: database
data:
  POSTGRES_DB: "catalogdb"
  POSTGRES_USER: "admin"
  POSTGRES_INITDB_ARGS: "-E UTF8 --locale=en_US.UTF-8"
