apiVersion: v1
kind: Secret
metadata:
  name: postgres-catalog-secret
  namespace: fiap-gamestore
  labels:
    app: postgres-catalog
    component: database
type: Opaque
stringData:
  postgres-password: "admin123"
  postgres-connection-string: "Host=postgres-catalog-service;Port=5432;Database=catalogdb;Username=admin;Password=admin123"
