apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-api-config
  namespace: fiap-gamestore
  labels:
    app: gateway-api
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
