apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-users-config
  namespace: fiap-gamestore
  labels:
    app: postgres-users
    component: database
data:
  POSTGRES_DB: "users_db"
  POSTGRES_USER: "postgres"
  POSTGRES_INITDB_ARGS: "-E UTF8 --locale=en_US.UTF-8"
