apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-users-pvc
  namespace: fiap-gamestore
  labels:
    app: postgres-users
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: standard  # Ajuste conforme seu cluster
