apiVersion: v1
kind: Secret
metadata:
  name: postgres-users-secret
  namespace: fiap-gamestore
  labels:
    app: postgres-users
    component: database
type: Opaque
stringData:
  postgres-password: "postgres"
  postgres-connection-string: "Host=postgres-users-service;Port=5432;Database=users_db;Username=postgres;Password=postgres"
