aws_region               = "us-east-1"
environment              = "prod"
project_name             = "fcg"
platform_namespace       = "fcg-platform"
public_subnet_cidrs      = ["10.42.0.0/24", "10.42.1.0/24"]
private_subnet_cidrs     = ["10.42.10.0/24", "10.42.11.0/24"]
node_instance_types      = ["t3.medium"]
node_group_min_size      = 2
node_group_desired_size  = 2
node_group_max_size      = 4
db_instance_class        = "db.t4g.micro"
mq_instance_type         = "mq.t3.micro"
redis_node_type          = "cache.t4g.micro"
opensearch_instance_type = "t3.small.search"
