apiVersion: v1
kind: Secret
metadata:
  name: users-api-secret
  namespace: fiap-gamestore
  labels:
    app: users-api
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=postgres-users-service;Port=5432;Database=users_db;Username=postgres;Password=postgres"
  Jwt__Key: "super-secret-key-change-this-32bytes-min"
  RabbitMQ__Username: "guest"
  RabbitMQ__Password: "guest"
