apiVersion: v1
kind: Service
metadata:
  name: users-api-swagger
  namespace: fiap-gamestore
  labels:
    app: users-api
    component: api
    service-type: external
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
    nodePort: 30080
  selector:
    app: users-api
